language: python
python:
  - "nightly"
install:
  - pip install coveralls, coverage
script:
  - python -m unittest discover
  - coverage run --source=httplib3 -m unittest discover
after_success: coveralls
